name: Docker Image CI

on:
  push:
    tags:
      - "latest"
      - "*.*.*"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          suricata
        tags: |
          type=semver,pattern={{version}}
          type=raw
    
    - name: Build the Docker image
      uses: docker/build-push-action@v2.6.1
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        
